name: "OD SP File Upload"
description: "Upload a file, or files, to SharePoint Online(one drive) using client secrets"
author: "German Nina"
branding:
  color: "blue"
  icon: "upload-cloud"
inputs:
  site_url:
    description: "Destination SPO Site URL"
    required: true
  clientId:
    description: "Must have write privileges on designated site."
    required: true
  clientSecret:
    description: "SPO account password."
    required: true
  realm:
    description: "SPO realm."
    required: true
  destination_path:
    description: "Relative destination path on SPO site. If path does not exist, it will be created."
    required: false
  source_path:
    description: "Source file paths to be uploaded to SPO. Separate multiple files using a semicolon."
    required: true
runs:
  using: "node16"
  
  - name: Install Dependencies
    shell: bash
    run: npm install

  - name: Upload files
    shell: bash
    run: node ./index.js